apiVersion: v1
kind: Pod
metadata:
  name: terraform
spec:
  containers:
    - name: terraform
      image: hashicorp/terraform:1.6.2 
      volumeMounts:
        - name: gcp-credentials-volume
          mountPath: /var/secrets/gcp
          readOnly: true
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/gcp/gcp-credentials.json # Path to the credentials file inside the pod
      command: ["/bin/sh", "-c"]
      args:
        - |
          apk add --no-cache git && \
          git clone https://github.com/hamid659/abridge-test.git /abridge-test && \
          cd /abridge-test/scripts && \
          chmod +x run_terraform.sh && \
          ./run_terraform.sh

  volumes:
    - name: gcp-credentials-volume
      secret:
        secretName: gcp-credentials-secret
